name: PR Title Check
on:
  pull_request:
    types: [opened, edited, synchronize]

jobs:
  check-title:
    runs-on: ubuntu-latest
    steps:
      - name: Validate PR title
        uses: actions/github-script@v7
        with:
          script: |
            const titleRaw = (context.payload.pull_request.title || "").trim();
            const TYPES = ["FEAT","FIX","REFACTOR","COMMENT","STYLE","TEST","CHORE","INIT"];

            // 형식: [TYPE]: 제목
            const m = titleRaw.match(/^\s*\[([A-Za-z]+)\]\s*:\s*(.+)\s*$/);
            if (!m) {
              core.setFailed("PR 제목 형식은 `[TYPE]: 제목` 이어야 합니다. 예: `[FEAT]: 회원가입 기능 추가`");
              return;
            }

            // TYPE 검증(대소문자 허용 → 내부적으로 대문자 비교)
            const type = m[1].toUpperCase();
            if (!TYPES.includes(type)) {
              core.setFailed(`TYPE은 ${TYPES.join(", ")} 중 하나여야 합니다.`);
              return;
            }

            // Subject 추출 및 트리밍
            const subject = m[2].trim();

            // 제목에 이슈번호 금지
            if (/\(#\d+\)|#\d+\b/.test(subject)) {
              core.setFailed("제목에 이슈번호를 넣지 마세요. 이슈는 액션이 자동 생성/연결합니다.");
              return;
            }

            // 길이 제한: 50자 (유니코드 코드포인트 기준)
            const subjectLen = [...subject].length;
            if (subjectLen < 1 || subjectLen > 50) {
              core.setFailed(`제목(Subject)은 1~50자 이내여야 합니다. 현재 ${subjectLen}자`);
              return;
            }

            core.info("PR title OK.");
